# This workflow will install Python dependencies and run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install flake8 pytest-cov
        pip install -r requirements.txt
    - name: Setup backend
      run: |
        cd ..
        git clone https://github.com/debiai/debiai.git
        cd debiai/backend
        pip install flask_cors connexion swagger-ui-bundle scipy ujson sklearn
        python websrv.py &
        cd ../../
        ls
        cd py-debiai
    - name: Test with pytest
      run: |
        pytest --cov=debiai -s
